Run unit tests in all OS
massalabs/station pull request #1044
Opened 2023-07-24 09:52 UTC by Thykof

2023-07-25 13:04 UTC, thomas-senechal requested changes
Looks good to me
But tests on Windows are failing :(

2023-07-26 13:14 UTC, Thykof commented
> Looks good to me But tests on Windows are failing :(

I fixed by using filePath.Join for the paths in the tests.

2023-07-26 13:47 UTC, thomas-senechal approved these changes

2023-07-28 07:55 UTC, peterjah commented on .github/workflows/tests.yml
> +          - os: macos-latest
`- os: ["windows-latest", "ubuntu-latest", "macos-latest"]`

2023-07-28 07:58 UTC, peterjah approved these changes

2023-07-28 08:29 UTC, merged