do not delete wallet files
massalabs/station pull request #1053
Opened 2023-07-26 08:49 UTC by peterjah

2023-07-26 15:05 UTC, Thykof approved these changes
code complexity can be reduce by writing small functions.

I tested on macos it works as expected.

2023-07-28 07:19 UTC, gregLibert requested changes

2023-07-28 07:19 UTC, gregLibert commented on pkg/plugin/manager.go
>  	}
You could improve your code by:
- changing the order of your if and return earlier
- put all that in a removePlugin function
- unit test the removePlugin function

My suggestion:
```suggestion
	err = removePlugin(plgn)
	if err != nil {
		return fmt.Errorf("deleting plugin %s: %w", correlationID, err)
	} 
	
```

With the following function:
```golang
// removePlugin removes all the plugin files from the file system.
// However, for the "massa-labs/massa-wallet" plugin, it keeps the wallet files.
// The wallet files are identified by the prefix "wallet_" and the suffix ".yaml".
func removePlugin(plugin *Plugin) error {
	dir := filepath.Dir(plugin.BinPath)

	alias := Alias(plugin.info.Author, plugin.info.Name)
	if alias != "massa-labs/massa-wallet" {
		return os.RemoveAll(dir)
	}

	// for the massa-wallet we want to keep all the wallet entries
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	for _, entry := range entries {
		if !(strings.HasPrefix(entry.Name(), "wallet_") && strings.HasSuffix(entry.Name(), ".yaml")) {
			err = os.RemoveAll(filepath.Join(dir, entry.Name()))
			if err != nil {
				return err
			}
		}
	}

	return nil
}
```
The matching unit test:
```golang
func Test_removePlugin(t *testing.T) {
	testCases := []struct {
		name        string
		plugin      *Plugin
		createFiles []string
		remainFiles []string
	}{
		{
			name: "massa-labs/massa-wallet",
			plugin: &Plugin{
				info: &Information{
					Author: "massa-labs",
					Name:   "massa-wallet",
				},
			},
			createFiles: []string{"wallet_test.yaml", "other_file.txt"},
			remainFiles: []string{"wallet_test.yaml"},
		},
		{
			name: "massa-labs/not-massa-wallet",
			plugin: &Plugin{
				info: &Information{
					Author: "massa-labs",
					Name:   "massa-wallet",
				},
			},
			createFiles: []string{"wallet_test.yaml", "other_file.txt"},
			remainFiles: []string{},
		},
		{
			name: "not-massa-labs/massa-wallet",
			plugin: &Plugin{
				info: &Information{
					Author: "massa-labs",
					Name:   "massa-wallet",
				},
			},
			createFiles: []string{"wallet_test.yaml", "other_file.txt"},
			remainFiles: []string{},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Create a temporary directory for testing.
			tempDir, err := ioutil.TempDir("", "plugin_test")
			if err != nil {
				t.Fatalf("Failed to create temp directory: %v", err)
			}

			tc.plugin.BinPath = filepath.Join(tempDir, "pluginBinary")

			// Create dummy files.
			for _, file := range tc.createFiles {
				dummyFile := filepath.Join(tempDir, file)
				if err := ioutil.WriteFile(dummyFile, []byte("test"), 0666); err != nil {
					t.Fatalf("Failed to create dummy file: %v", err)
				}
			}

			// Call the function to test.
			if err := removePlugin(tc.plugin); err != nil {
				t.Fatalf("Failed to remove plugin: %v", err)
			}

			// Check if the remaining files still exist.
			for _, file := range tc.remainFiles {
				dummyFile := filepath.Join(tempDir, file)
				if _, err := os.Stat(dummyFile); os.IsNotExist(err) {
					t.Fatalf("File was deleted: %v", err)
				}
			}

			// Clean up the temporary directory.
			os.RemoveAll(tempDir)
		})
	}
}
```

2023-07-28 13:55 UTC, gregLibert approved these changes

2023-07-28 13:55 UTC, merged

2023-08-16 07:17 UTC, Thykof commented
> * Tested on MacOS M1 - done.
> 
>     * Needs test for:
>       Linux
>       Windows

Great, it's the same behavior in all OS. No need to test on other OS if it work on one of them

2023-08-16 08:02 UTC, longgamma-massa commented
@Thykof there might be a problem now. 

1. The wallet recognized my accounts when I tried to add them to the 'main' version. 
2. Now I downgraded to the latest-release version, the yaml files are saved on my computer, but there's no way to import them. I get 'filesystem error.
<img width="479" alt="image" src="https://github.com/massalabs/station/assets/113043914/f861f384-8c0e-4fb9-8c79-f2fdc5347e97">

2023-08-16 08:11 UTC, longgamma-massa commented
UPDATE: I think I found the issue (it was my old wallet.yaml) but would be great if you Q/A as well @Thykof

2023-08-16 09:37 UTC, Thykof commented
I tested is works as expected:

- install the wallet plugin
- create or import an account
- remove the wallet plugin
- install it again
- see that your account is accessible from the plugin