add decoder for execute sC
massalabs/station pull request #1104
Opened 2023-08-17 08:20 UTC by B-Naoufal

2023-08-17 14:35 UTC, Thykof requested changes

2023-08-17 14:35 UTC, Thykof commented on pkg/node/sendoperation/executesc/executesc.go
> +	OperationID uint64
unused

```suggestion
```

2023-08-17 15:32 UTC, Thykof approved these changes

2023-08-18 07:27 UTC, thomas-senechal approved these changes

2023-08-18 07:30 UTC, merged