Add error message for unsupported Windows versions
massalabs/station pull request #1216
Opened 2023-10-04 08:28 UTC by thomas-senechal

## Delivery Quality Checklist

- [ ] **Breaking Changes in API:**
  Does this PR introduce breaking changes in the API?
    - If yes, have you considered making it backward compatible?
    - If backward compatibility is not considered, set the "breaking-change" label.

- [ ] **Changelog:**
  - [ ] For bugfix PR, set the "bugfix" label
  - [ ] If this change should not appear in changelog, use "ignore-for-changelog" label

- [ ] **Version Update Handling:**
  Have you ensured that the version update by user is handled correctly?

- [ ] **PR Dependency:**
  Does this PR depend on another PR?
    - If yes, is it necessary for the dependency to be released prior to merging this one?

- [ ] **Documentation:**
  - [ ] Are any necessary changes made to user-facing documentation?
  - [ ] Confirm that API documentation is updated with any relevant changes.
  - [ ] Check that README and other documentation files are accurate and current.

2023-10-04 08:30 UTC, gregLibert requested changes

2023-10-04 08:31 UTC, thomas-senechal commented on installer/windows/build_installer.py
> +            <![CDATA[Installed OR (VersionNT >= 603 AND MsiNTProductType = 1)]]>
https://learn.microsoft.com/en-us/troubleshoot/windows-client/application-management/versionnt-value-for-windows-10-server

Windows is a nightmare 😭

2023-10-04 08:36 UTC, thomas-senechal commented on installer/windows/build_installer.py
> +            <![CDATA[Installed OR (VersionNT >= 603 AND MsiNTProductType = 1)]]>
And here they say 603 is for W8.1
https://learn.microsoft.com/en-us/windows/win32/msi/operating-system-property-values

2023-10-04 08:37 UTC, thomas-senechal commented on installer/windows/build_installer.py
> +            <![CDATA[Installed OR (VersionNT >= 603 AND MsiNTProductType = 1)]]>
And in my installer logs, it says I'm at 603

2023-10-04 08:38 UTC, thomas-senechal commented on installer/windows/build_installer.py
> +            <![CDATA[Installed OR (VersionNT >= 603 AND MsiNTProductType = 1)]]>
> The installer sets the VersionNT property to the version number for the operating system, undefined if the operating system is not Windows NT, Windows 2000, Windows XP, Windows Vista, Windows Server 2008, or Windows 7. The value is an integer: MajorVersion * 100 + MinorVersion

https://learn.microsoft.com/en-us/windows/win32/msi/versionnt

2023-10-04 08:51 UTC, thomas-senechal commented on installer/windows/build_installer.py
> +            <![CDATA[Installed OR (VersionNT >= 603 AND MsiNTProductType = 1)]]>
https://stackoverflow.com/q/71647237 🫠

2023-10-04 09:12 UTC, thomas-senechal commented on installer/windows/build_installer.py
> +            <![CDATA[Installed OR (VersionNT >= 603 AND MsiNTProductType = 1)]]>
![image](https://github.com/massalabs/station/assets/44696378/e0af711c-1dcb-41eb-8e67-5c69d9bbffd6)
Using Build number

2023-10-04 12:02 UTC, gregLibert approved these changes

2023-10-04 12:03 UTC, pivilartisant approved these changes

2023-10-04 12:11 UTC, Thykof approved these changes

2023-10-09 09:35 UTC, merged

2023-10-09 09:39 UTC, thomas-senechal commented
Just for the record, to test this, you need either to have a Windows prior to W10, or, modify the `WINDOWSEDITION` ( https://github.com/massalabs/station/pull/1216/files#diff-40085a0c3f8a1d74e1ec5324db618bbced740670ce3324856c05f60f09b4245bR170 ) to a version after yours (or one that does not exists yet)