1269 read only execute sc
massalabs/station pull request #1273
Opened 2023-11-16 23:32 UTC by Thykof

## Delivery Quality Checklist

- [ ] **Breaking Changes in API:**
  Does this PR introduce breaking changes in the API?
    - If yes, have you considered making it backward compatible?
    - If backward compatibility is not considered, set the "breaking-change" label.

- [ ] **Changelog:**
  - [ ] For bugfix PR, set the "bugfix" label
  - [ ] If this change should not appear in changelog, use "ignore-for-changelog" label

- [ ] **Version Update Handling:**
  Have you ensured that the version update by user is handled correctly?

- [ ] **PR Dependency:**
  Does this PR depend on another PR?
    - If yes, is it necessary for the dependency to be released prior to merging this one?

- [ ] **Documentation:**
  - [ ] Are any necessary changes made to user-facing documentation?
  - [ ] Confirm that API documentation is updated with any relevant changes.
  - [ ] Check that README and other documentation files are accurate and current.

2023-12-19 08:42 UTC, peterjah commented on pkg/onchain/sc.go
> +	if maxGas == sendOperation.DefaultGasLimitExecuteSC || maxGas == 0 {
this condition is strange, if we dont want to use DefaultGasLimitExecuteSC, we should delete it and do the estimation only when maxgas is not provided

2023-12-20 08:50 UTC, thomas-senechal approved these changes

2023-12-20 10:13 UTC, peterjah approved these changes

2023-12-20 10:23 UTC, peterjah requested changes
from the swagger file:
```
              maxGas:
                $ref: "#/definitions/Amount"
                description: Maximum number of gas unit that a operation will be able consume.
                default: 700000000 # DefaultGasLimit
```
  
```
  Amount:
    description: Amount in nanoMassa.
    type: string
    x-nullable: false
```

    I think there is better to do here.
    I suggest to allow amount to be nullable here, and if null, do the estimation.
    If we don't want to change the behaviour everywhere, you can create a new swagger type 'nullableAmount' by instance...

2023-12-20 13:42 UTC, peterjah approved these changes

2023-12-20 14:36 UTC, merged