Windows add shortcuts
massalabs/station pull request #745
Opened 2023-06-13 14:04 UTC by thomas-senechal

Adds a shortcut in the StartMenu and on the Desktop of the user.

2023-06-15 13:48 UTC, gregLibert requested changes

2023-06-15 13:48 UTC, gregLibert commented on installer/windows/build_installer.py
> +MANUFACTURER = "Massa Labs"
```suggestion
MANUFACTURER = "MassaLabs"
```

2023-06-16 08:10 UTC, gregLibert approved these changes

2023-06-19 07:33 UTC, B-Naoufal approved these changes

2023-06-19 08:02 UTC, merged