Implement XSS protection and refactor duplicate code in search and websiteuploader pages
massalabs/station pull request #793
Opened 2023-06-19 09:53 UTC by B-Naoufal

2023-06-19 12:32 UTC, peterjah approved these changes

2023-06-19 13:55 UTC, Thykof approved these changes

2023-06-19 13:55 UTC, Thykof commented on pkg/dnshelper/dnshelper.go
> +	escapedDescription := template.HTMLEscapeString(websiteDescription)
this peace of code is not optimal: if `len(websiteValue) > indexOfWebsiteDescription` is false, then we will call `HTMLEscapeString` for nothing

2023-06-19 13:55 UTC, Thykof commented on pkg/dnshelper/dnshelper.go
> +	escapedDescription := template.HTMLEscapeString(websiteDescription)
I would suggest to call `HTMLEscapeString` inside the if statement

2023-06-19 14:23 UTC, gregLibert requested changes

2023-06-19 14:23 UTC, gregLibert commented on pkg/dnshelper/dnshelper.go
> +// Helper function to fetch website values from DNS entry.
As you function signature is ambiguous, you should describe the returned values explaining that the first one is an address and the second on is the description content.

Furthermore, you should avoid using word such as get or fecth we you don't grab the infomration from a remote service. here you are simply converting it.

Something as simple as the following should be sufficent:

```suggestion
// AddressAndDescription fetch the website address and it's description from the DNS entry.
```

2023-06-19 14:23 UTC, gregLibert commented on pkg/dnshelper/dnshelper.go
> +	websiteValue := convert.ByteToStringArray(dnsValue)
You use websiteValue a lot. You should clarify what your are manipulating using a clearer functin name
```suggestion
	dnsRecords := convert.ByteToStringArray(dnsValue)
```

2023-06-19 14:23 UTC, gregLibert commented on pkg/dnshelper/dnshelper.go
> +	websiteStorerAddress := websiteValue[indexOfWebsiteAddress]
Same, we alreadu know that the this is a DNS for a website. you can simply the varaible name:
```suggestion
	address := websiteValue[indexOfWebsiteAddress]
```

2023-06-19 14:23 UTC, gregLibert commented on pkg/dnshelper/dnshelper.go
> +	escapedDescription := template.HTMLEscapeString(websiteDescription)
Same as @Thykof with a clearer variable name:
```suggestion
	descrition := ""
	if len(websiteValue) > indexOfWebsiteDescription {
	// Prevent XSS by escaping the HTML content.
	// see https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#output-encoding-for-html-contexts
		description = template.HTMLEscapeString(websiteDescription)
	}
```

2023-06-19 14:23 UTC, gregLibert commented on pkg/dnshelper/dnshelper.go
> +// Helper function to retrieve website metadata.
```suggestion
// GetWebsiteMetadata retrieves candidate metadata of the website.
```

2023-06-19 14:23 UTC, gregLibert commented on pkg/dnshelper/dnshelper.go
> +func GetWebsiteValues(dnsValue []byte) (string, string, error) {
Can you please unit test this function to be sure that the XSS attack is indeed aborted?

2023-06-20 12:05 UTC, gregLibert approved these changes
One facultative comment to clarify that the content of the DNS should not be trusted. It's optional.

2023-06-20 12:05 UTC, gregLibert commented on pkg/dnshelper/dnshelper.go
> +		websiteDescription := dnsRecords[indexOfWebsiteDescription]
```suggestion
		unsafeDescription := dnsRecords[indexOfWebsiteDescription]
```

2023-06-20 13:33 UTC, merged