717 write logs on disk
massalabs/station pull request #899
Opened 2023-06-28 07:18 UTC by Pierregvx

2023-06-28 10:11 UTC, gregLibert requested changes

2023-06-28 10:11 UTC, gregLibert commented on cmd/massastation/main.go
> +}
```suggestion
func newLogger() *logger {
	logDir, err := config.GetConfigDir()
	if err != nil {
		log.Fatal(err)
	}

	logFilePath := filepath.Join(logDir, "massastation.log")
	
	rawJSON := []byte(`{
	  "level": "info",
	  "encoding": "json",
	  "outputPaths": ["stdout", "` + logFilePath + `"],
	  "errorOutputPaths": ["stderr", "` + logFilePath + `"]
	}`)

	var cfg zap.Config
	if err := json.Unmarshal(rawJSON, &cfg); err != nil {
		panic(err)
	}
	return zap.Must(cfg.Build())
}
```

2023-06-28 10:11 UTC, gregLibert commented on cmd/massastation/main.go
> +	defer logger.close()
```suggestion
	defer logger.Sync()
```

2023-06-28 13:58 UTC, peterjah requested changes
little thing to fix, but good job!

2023-06-28 13:58 UTC, peterjah commented on cmd/massastation/main.go
> +		config.Logger.Error(fmt.Sprintf("Unable to read cert dir:%s\n%s", err,
i think this is not iso functionnal. Fatalln will exit the app. and i dont think config.Logger.Error wil do the same.
or you keep log.Fatalln here. or you have to add a  os.Exit(1) after this line

2023-06-28 13:58 UTC, peterjah commented on cmd/massastation/main.go
> +		config.Logger.Error(fmt.Sprintf("Failed to create NetworkManager:%s", err))
same here

2023-06-28 14:18 UTC, peterjah approved these changes

2023-06-28 16:11 UTC, gregLibert requested changes
You should replace fmt;Sprintf if possible by uisng XXXf functions. the code will be simpler to read.

2023-06-28 16:11 UTC, gregLibert commented on cmd/massastation/main.go
> +		config.Logger.Error(fmt.Sprintf("Unable to read config dir: %s\n%s", err, "MassaStation can't run without a config directory.\nPlease reinstall MassaStation using the installer at https://github.co
Errorf ?

2023-06-28 16:11 UTC, gregLibert commented on cmd/massastation/main.go
> +		config.Logger.Fatal(fmt.Sprintf("Unable to read cert dir:%s\n%s", err,
Fatalf ?

2023-06-28 16:11 UTC, gregLibert commented on int/api/server.go
> +		config.Logger.Error(err.Error())
should be a fatal

2023-06-28 16:11 UTC, gregLibert commented on int/api/server.go
> +		config.Logger.Error(err.Error())
should be a fatal

2023-06-28 16:11 UTC, gregLibert commented on pkg/config/network.go
> +	Logger.Info(fmt.Sprintf("Current config: %+v\n", n.Network()))
Should be debug

2023-06-28 16:11 UTC, gregLibert commented on pkg/convert/byteConverter.go
> +		config.Logger.Info(fmt.Sprintf("error converting bytesToU64 :%v\n", err))
should be an error

2023-06-28 16:11 UTC, gregLibert commented on pkg/plugin/plugin.go
> +		config.Logger.Info(fmt.Sprintf("plugin '%s' exiting without error.\n", pluginName))
should be a debug

2023-06-28 16:11 UTC, gregLibert commented on pkg/plugin/plugin.go
> +	config.Logger.Info(fmt.Sprintf("Stopping plugin %s.\n", p.ID))
should be a debug

2023-06-28 16:11 UTC, gregLibert commented on pkg/store/store.go
> +		config.Logger.Info(fmt.Sprintf("Fetched plugin list. %d plugins in store.", len(s.Plugins)))
should be a debug

2023-06-28 16:44 UTC, Pierregvx commented
> You should replace fmt;Sprintf if possible by uisng XXXf functions. the code will be simpler to read.

I couldn't see these functions in https://github.com/uber-go/zap/blob/master/logger.go
but maybe I can use an addition ?

2023-06-29 08:35 UTC, gregLibert approved these changes

2023-06-29 08:37 UTC, gregLibert commented on pkg/config/logger.go
> +func NewLogger() *zap.Logger {
ok, I cleaned it to much, my bad...

2023-06-29 09:04 UTC, merged

2023-06-30 08:14 UTC, Thykof commented on pkg/config/logger.go
> +	logFilePath := filepath.Join(logDir, "massastation.log")
logFilePath := filepath.Join(logDir, "logs, "massastation.log")