validate file size
massalabs/station pull request #936
Opened 2023-06-30 14:10 UTC by B-Naoufal

2023-06-30 14:27 UTC, Thykof requested changes

2023-06-30 14:27 UTC, Thykof commented on web/massastation/src/components/SidePanels/Upload/Upload.tsx
> +      console.log('my function is working ....');
```suggestion
```

2023-06-30 14:27 UTC, Thykof commented on web/massastation/src/i18n/en_US.json
> +      "upload-error": "Failed to upload website psisi.",
```suggestion
      "upload-error": "Failed to upload website.",
```

2023-06-30 14:27 UTC, Thykof commented on web/massastation/src/validation/upload.ts
> +export async function validateFileSize(file: File): Promise<boolean> {
this function doesn't need to be async.

2023-07-03 09:41 UTC, pivilartisant approved these changes

2023-07-03 09:50 UTC, merged