Add Logo On Windows
massalabs/station pull request #968
Opened 2023-07-06 09:48 UTC by pivilartisant

2023-07-10 08:12 UTC, Thykof requested changes

2023-07-10 08:12 UTC, Thykof commented on installer/windows/build_installer.py
> +                            Target="[#MassaStationAppEXE]"
you changed from MassaStationRunScript to MassaStationAppEXE. Tell me the windows cmd terminal stays open with MassaStationAppEXE.


```suggestion
                            Target="[#MassaStationRunScript]"
```

2023-07-10 09:47 UTC, Thykof approved these changes

2023-07-11 07:57 UTC, Pierregvx approved these changes

2023-07-11 08:58 UTC, merged